// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fix_status_timestamps
IntegerVector fix_status_timestamps(IntegerVector timestamp, IntegerVector adv_timestamp);
RcppExport SEXP _mlabtools_fix_status_timestamps(SEXP timestampSEXP, SEXP adv_timestampSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type timestamp(timestampSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type adv_timestamp(adv_timestampSEXP);
    rcpp_result_gen = Rcpp::wrap(fix_status_timestamps(timestamp, adv_timestamp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mlabtools_fix_status_timestamps", (DL_FUNC) &_mlabtools_fix_status_timestamps, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_mlabtools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
