# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fix status timestamp jitter
#'
#' Looks for timestamps same as previous timestamp.
#' Adds 1s to duplicate timestamp
#' If there is 1s gap after previous timestamp,
#' and gap is not in ADV timestamp, remove gap.
#'
#' @param timestamp A vector of status timestamps
#' @param adv_timestamp A vector of adv status timestamps
#' @return The corrected timestamp vector
fix_timestamp_jitter <- function(timestamp, adv_timestamp) {
    .Call(`_gemstools_fix_timestamp_jitter`, timestamp, adv_timestamp)
}

